/** @type {import('tailwindcss').Config} */
export default {
  content: ['./*.html', './partials/**/*.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand accents (DESIGN.md)
        navy: '#0A192F',
        teal: '#008080',
        gold: { DEFAULT: '#C5A059', light: '#d4b373' },
        emerald: '#047857',

        // Design-system tokens
        'on-primary-container': '#76849f',
        'tertiary-fixed-dim': '#7bd8b1',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#004f4f',
        'on-tertiary-fixed': '#002115',
        'surface-container-high': '#e6e8ea',
        error: '#ba1a1a',
        'surface-dim': '#d8dadc',
        tertiary: '#000000',
        secondary: '#006a6a',
        'inverse-primary': '#b9c7e4',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        surface: '#f7f9fb',
        'primary-fixed': '#d6e3ff',
        background: '#f7f9fb',
        'on-tertiary-container': '#339471',
        'primary-container': '#0d1c32',
        'on-primary-fixed': '#0d1c32',
        'surface-bright': '#f7f9fb',
        'on-surface-variant': '#44474d',
        'outline-variant': '#c5c6cd',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#97f5cc',
        'on-error-container': '#93000a',
        'surface-container-low': '#f2f4f6',
        primary: '#000000',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#76d6d5',
        'tertiary-container': '#002115',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed-variant': '#00513a',
        'on-background': '#191c1e',
        'on-primary-fixed-variant': '#39475f',
        'primary-fixed-dim': '#b9c7e4',
        'on-secondary-container': '#006e6e',
        'surface-tint': '#515f78',
        outline: '#75777e',
        'surface-variant': '#e0e3e5',
        'surface-container': '#eceef0',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        'error-container': '#ffdad6',
        'secondary-fixed': '#93f2f2',
        'on-surface': '#191c1e',
        'secondary-container': '#90efef',
        'on-secondary-fixed': '#002020',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        gutter: '24px',
        // Page gutters: mobile-first, widened at md via `md:px-margin-desktop`
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'title-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        // Level 1 / Level 2 ambient elevation from DESIGN.md
        'ambient-1': '0 4px 12px rgba(10, 25, 47, 0.04)',
        'ambient-2': '0 8px 24px rgba(10, 25, 47, 0.08)',
      },
      screens: {
        xs: '420px',
      },
    },
  },
  plugins: [],
};
